stages:
  - test
  - build
  - preview
  - staging
  - production

image: zoltannz/python-with-gcloud

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"
  PIPENV_VENV_IN_PROJECT: "true"
  LANG: "en_NZ.UTF-8"
  LC_ALL: "en_NZ.UTF-8"
  FLASK_APP: "flaskr"
  FLASK_ENV: "production"
  DEBUG: "false"

cache:
  paths:
    - .cache/pip
    - .cache/pipenv
    - .venv/

before_script:
  - python -V # Print out python version for debugging
  - pip install pipenv
  - pipenv run setup

test:
  stage: test
  script:
    - pipenv run lint
    - pipenv run test
    - pipenv run cov-report

build:
  stage: build
  script:
    - pipenv run build
    - echo $GC_SERVICE_ACCOUNT_KEY > gc-service-key.json
    - gcloud auth activate-service-account --key-file gc-service-key.json
    - gcloud builds --project ${GC_PROJECT_ID} submit --tag gcr.io/${GC_PROJECT_ID}/flask-playground:latest .