image: zoltannz/python-with-gcloud

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"
  PIPENV_VENV_IN_PROJECT: 1
  LANG: "en_NZ.UTF-8"
  LC_ALL: "en_NZ.UTF-8"
  FLASK_APP: flaskr
  FLASK_ENV: production
  DEBUG: 0

cache:
  paths:
    - .cache/pip
    - .cache/pipenv
    - .venv/

before_script:
  - python -V # Print out python version for debugging
  - pip install pipenv
  - pipenv run setup

test:
  script:
    - pipenv run lint
    - pipenv run test
    - pipenv run cov-report