apiVersion: v1
kind: Namespace
metadata:
  name: flaskr

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: flaskr-${IMAGE_TAG}
  name: flaskr-admin-service-account
  namespace: flaskr

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flaskr
  name: flaskr-admin-role
rules:
  - apiGroups: ["*"]
    resources: ["ResourceAll"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: be-flaskr-admin
  namespace: flaskr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: flaskr-admin-role
  kind: Role
subjects:
- kind: ServiceAccount
  name: flaskr-admin-service-account
  namespace: flaskr

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/db-pv-volume"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  namespace: flaskr
  labels:
    app: flaskr-${IMAGE_TAG}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskr-review-deployment-${IMAGE_TAG}
  namespace: flaskr
  labels:
    app: flaskr-${IMAGE_TAG}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskr-${IMAGE_TAG}
  template:
    metadata:
      labels:
        app: flaskr-${IMAGE_TAG}
    spec:
      containers:
        - name: flaskr
          image: flaskr:${IMAGE_TAG}
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: /home/app/db
              name: db
      initContainers:
        - name: flaskr-init
          image: flaskr:${IMAGE_TAG}
          imagePullPolicy: Never
          command: ['flask', 'init-db']
          volumeMounts:
            - mountPath: /home/app/db
              name: db
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskr-${IMAGE_TAG}
  name: flaskr-review-load-balancer-${IMAGE_TAG}
  namespace: flaskr
spec:
  selector:
    app: flaskr-${IMAGE_TAG}
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 8080
  type: LoadBalancer