apiVersion: v1
kind: Namespace
metadata:
  name: flaskr-review

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flaskr-review-persistent-volume-claim
  namespace: flaskr-review
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskr-review-deployment
  namespace: flaskr-review
  labels:
    app: flaskr-review-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskr-review-app
  template:
    metadata:
      labels:
        app: flaskr-review-app
    spec:
      securityContext:
        fsGroup: 1024
      containers:
        - name: flaskr-review
          image: gcr.io/{{GC_PROJECT_ID}}/flask-playground:review-1
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: /home/app/db
              name: db
      initContainers:
        - name: flaskr-init
          image: gcr.io/{{GC_PROJECT_ID}}/flask-playground:review-1
          command: ['flask', 'init-db']
          volumeMounts:
            - mountPath: /home/app/db
              name: db
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: flaskr-review-persistent-volume-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskr-review-app
  name: flaskr-review-node-port
  namespace: flaskr-review
spec:
  selector:
    app: flaskr-review
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 8080
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskr-review-app
  name: flaskr-review-load-balancer
  namespace: flaskr-review
spec:
  selector:
    app: flaskr-review-app
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 8080
  type: LoadBalancer